projeto/core/urls.py
from django.urls import path
from projeto.core import views as v


app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),
]

projeto/produto/urls.py
from django.urls import path
from projeto.produto import views as v

'''Tratamento das URLs do projeto '''

app_name = 'produto'

urlpatterns = [
    path('', v.ProdutoList.as_view(), name='produto_list'), # apresenta todos os produtos
    path('<int:pk>/', v.produto_detail, name='produto_detail'), # exibe o produto a partir da sua PK
    path('add/', v.ProdutoCreate.as_view(), name='produto_add'), # cria um novo produto
    path('<int:pk>/edit/', v.ProdutoUpdate.as_view(), name='produto_edit'), # edita um produto
    path('<int:pk>/json/', v.produto_json, name='produto_json'), # exibe o produto em formato json
]

projeto/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import include, path

urlpatterns = [
    path('', include('projeto.core.urls')),
    path('produto/', include('projeto.produto.urls')),
    
]

projeto/core/models.py
from django.db import models

'''
class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True
'''

projeto/pedido/models.py
from django.db import models

# Create your models here.

projeto/produto/models.py
from django.db import models
from django.urls import reverse_lazy

class Produto(models.Model):
    '''Model para o produto '''

    disponivel = models.BooleanField(default=True)    
    produto = models.CharField(max_length=100, unique=True)
    preco = models.DecimalField('preço', max_digits=7, decimal_places=2)
    quantidade = models.IntegerField('quantidade')
    

    class Meta:
        ordering = ('produto',)

    def __str__(self):
        return self.produto

    def get_absolute_url(self):
        return reverse_lazy('produto:produto_detail', kwargs={'pk': self.pk})

    def to_dict_json(self):
        return {
            'pk': self.pk,
            'produto': self.produto,
            'quantidade': self.quantidade,
        }

projeto/produto/forms.py
from django import forms
from .models import Produto


class ProdutoForm(forms.ModelForm):

    class Meta:
        model = Produto
        fields = '__all__'

projeto/core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

projeto/pedido/views.py
from django.shortcuts import render

# Create your views here.

projeto/produto/views.py
from django.contrib import messages
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, ListView
from .models import Produto
from .forms import ProdutoForm


def produto_list(request):
    '''
    Trata uma requisição web e recupera os produtos renderizando em um html
    '''
    template_name = 'produto_list.html'
    objects = Produto.objects.all()
    search = request.GET.get('search')
    if search:
        objects = objects.filter(produto__icontains=search)
    context = {'object_list': objects}
    return render(request, template_name, context)


class ProdutoList(ListView):
    '''
    Exibe os produtos, a cada 10 registros
    '''
    model = Produto
    template_name = 'produto_list.html'
    paginate_by = 10

def produto_detail(request, pk):
    '''
    Permite a alteracao de um produto
    '''
    template_name = 'produto_detail.html'
    obj = Produto.objects.get(pk=pk)
    context = {'object': obj}
    return render(request, template_name, context)


def produto_add(request):
    '''
    Trata uma requisição web e exibe um form para cadastro de produto
    '''
    template_name = 'produto_form.html'
    return render(request, template_name)


class ProdutoCreate(CreateView):
    '''
    Cria o form para adicao de novos produtos
    '''
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm


class ProdutoUpdate(UpdateView):
    '''
    Cria o form para alteracao produtos
    '''
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm


def produto_json(request, pk):
    ''' 
    Retorna o produto, id e quantidade. 
    '''
    produto = Produto.objects.filter(pk=pk)
    data = [item.to_dict_json() for item in produto]
    return JsonResponse({'data': data})


def save_data(data):
    '''
    Salva os dados no banco.
    '''
    aux = []
    for item in data:
        produto = item.get('produto')        
        disponivel = True if item.get('disponivel') == 'True' else False
        preco = item.get('preco')
        quantidade = item.get('quantidade')
        
        obj = Produto(
            produto=produto,            
            disponivel=disponivel,
            preco=preco,
            quantidade=quantidade,            
        )
        aux.append(obj)
    Produto.objects.bulk_create(aux)

projeto/core/templates/base.html
<!-- https://getbootstrap.com/docs/4.0/getting-started/introduction/#starter-template -->
<!-- Arquivo HTML básico que serve de modelo para os demais templates -->

{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
    <title>Pedido</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Font-awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Select2 -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block css %}{% endblock css %}

  </head>
  <body>

    {% include "includes/nav.html" %}

    <div class="container">
      {% block content %}{% endblock content %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- Select2 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

    {% block js %}{% endblock js %}
  </body>
</html>

projeto/core/templates/includes/nav.html
<!-- https://github.com/JTruax/bootstrap-starter-template/blob/master/template/start.html -->
<!-- HTML booststrap para a home do projeto -->

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:index' %}">Desafio Técnico <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Produtos</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'produto:produto_list' %}">Produtos</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pedido</a>
                <div class="dropdown-menu" aria-labelledby="dropdown02">
                    <a class="dropdown-item" href="{% url 'produto:produto_list' %}">Fazer pedido</a>                    
                </div>
                </div>
            </li>
            
        </ul>
        {% if user.is_authenticated %}
          <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
              <a href="{% url 'logout' %}" class="nav-link">Sair</a>
            </li>
          </ul>
        {% endif %}
    </div>
</nav>

projeto/core/templates/includes/pagination.html
<!-- Configura e implementa a navegação em mais de uma página  -->

<div class="row text-center">
  <div class="col-lg-12">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo;</a></li>
      {% endif %}

      {% for pg in page_obj.paginator.page_range %}
        <!-- Sempre mostra as 3 primeiras e 3 últimas páginas -->
        {% if pg == 1 or pg == 2 or pg == 3 or pg == page_obj.paginator.num_pages or pg == page_obj.paginator.num_pages|add:'-1' or pg == page_obj.paginator.num_pages|add:'-2' %}
          <li class="page-item"><a class="page-link" href="?page={{ pg }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a></li>
        {% else %}
          {% if page_obj.number == pg %}
            <li class="page-item active"><a class="page-link" href="?page={{ pg }}">{{ pg }}</a></li>
          {% elif pg > page_obj.number|add:'-4' and pg < page_obj.number|add:'4' %}
            <!-- Mostra 3 páginas antes e 3 páginas depois da atual -->
            <li class="page-item"><a class="page-link" href="?page={{ pg }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a></li>
          {% elif pg == page_obj.number|add:'-4' or pg == page_obj.number|add:'4' %}
            <li class="page-item"><a class="page-link" href="">...</a></li>
          {% endif %}
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&q={{ request.GET.q }}">&raquo;</a></li>
      {% endif %}
    </ul>
  </div>
</div>

projeto/core/templates/index.html
<!-- Index do projeto -->

{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
  <div class="container">
    <h1>Bem-vindo!</h1>
    <p>Este é um sistema para controle de produtos e pedidos.</p>
    <p>
      <a href="https://github.com/kevinsantana/desafio-tecnico-coopersystem">Veja no GitHub</a>
    </p>
  </div>
</div>

{% endblock content %}

projeto/produto/templates/produto_detail.html
<!-- Permite alterar um produto previamente cadastrado -->

{% extends "base.html" %}

{% block content %}

<a href="{% url 'produto:produto_list' %}">Voltar</a>

<h1>{{ object }}
  <span class="pull-right">
    <a href="{% url 'produto:produto_edit' object.pk %}">
      <button type="button" class="btn btn-success">
        <span class="fa fa-pencil"></span> Editar
      </button>
    </a>
  </span>
</h1>

<div class="col-sm-6">
  <table class="table table-user-information">
    <tbody>
      <tr>
        <th class="text-right">Disponivel</th>
        <td>
          {% if object.disponivel %}
            <i class="fa fa-check-circle ok"></i>
          {% else %}
            <i class="fa fa-minus-circle no"></i>
          {% endif %}
        </td>
      </tr>
      <tr>
        <th class="text-right">Produto</th>
        <td>{{ object.produto }}</td>
      </tr>
      <tr>
        <th class="text-right">Preço</th>
        <td>R$ {{ object.preco }}</td>
      </tr>
      <tr>
        <th class="text-right">Quantidade</th>
        <td>{{ object.estoque }}</td>
      </tr>      
      </tr>
    </tbody>
  </table>
</div>

{% endblock content %}

projeto/produto/templates/produto_form.html
<!-- Form para adicionar produto -->

{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}

<form method="POST" novalidate>
  {% csrf_token %}
  {% for field in form.visible_fields %}
    <div class="form-group{% if field.errors %} has-error {% endif%}">
      <label for="{{ field.id_for_label }}">
        {% if field.field.required %}
          <span class="required">{{ field.label }} </span>
        {% else %}
          {{ field.label }}
        {% endif %}
      </label>
      {% render_field field class="form-control" %}
      {% for error in field.errors %}
        <span class="text-muted">{{ error }}</span>
      {% endfor %}
    </div>
  {% endfor %}
  <button type="submit" class="btn btn-success">Cadastrar</button>
</form>

{% endblock content %}

{% block js %}

<script src="{% static 'js/produto.js' %}"></script>

{% endblock js %}

projeto/produto/templates/produto_list.html
<!-- Exibe uma lista em formato de tabela de todos os produtos cadastrados -->

{% extends "base.html" %}

{% block content %}

{% for message in messages %}
  {% if 'success' in message.tags %}
    <p class="alert alert-success" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
  {% else %}
    <p class="alert alert-danger" role="alert"><span style="font-weight: bold">{{ message }}</span></p>
  {% endif %}
{% endfor %}

<div class="row">
  <div class="col-sm-6">
    <form action="." method="GET" class="form-inline">
      <input type="text" id="search" name="search" class="form-control" placeholder="Busca">
      <input type="submit" class="btn btn-primary" style="margin-left: 10px;" value="OK">
    </form>
  </div>
</div>

<div class="page-header">
  <h2>Lista de Produtos
    <span class="pull-right">
      <a href="{% url 'produto:produto_add' %}">
        <button type="button" class="btn btn-primary">
          <span class="fa fa-plus"></span> Adicionar
        </button>
      </a>
    </span>
  </h2>

  {% if object_list %}
    
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Disponivel</th>          
          <th>Produto</th>
          <th>Preço</th>
          <th class="text-center">Quantidade</th>
         
        </tr>
      </thead>
      <tbody>
        {% for object in object_list %}
          <tr>
            <td>
              {% if object.disponivel %}
                <i class="fa fa-check-circle ok"></i>
              {% else %}
                <i class="fa fa-minus-circle no"></i>
              {% endif %}
            </td>
            
            <td>
              <a href="{{ object.get_absolute_url }}">{{ object.produto }}</a>
            </td>
            <td><span class="pull-left">{{ object.preco }}</span></td>
            <td class="text-center">{{ object.quantidade }}</td>
            
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p class="alert alert-warning">Sem itens na lista.</p>
  {% endif %}

</div>

{% include "includes/pagination.html" %}

{% endblock content %}

{% block js %}

<script>
  // Close alert after 2 seconds
  window.setTimeout(function() {
    $('.alert').fadeTo(500, 0).slideUp(500, function() {
      $(this).remove();
    });
  }, 2000);
</script>

{% endblock js %}